### PR TITLE
Fixes #1173

### LINKED ISSUE #1173: Error on API call
Dear CGRateS Team !

Please fix error on ApierV1.SetAttributeProfile while providing wrong Substitute field:
```
{
  "id":"0",
  "method":"ApierV1.SetAttributeProfile",
  "params":[
    {
      "Tenant":"golant",
      "ID":"ATTR_972587832508_SESSIONAUTH",
      "Contexts":["*sessions","*cdrs"],
      "FilterIDs":["*string:Account:972587832508"],
      "Attributes":[
          {
            "FieldName":"Category",
            "Initial": "*any",
            "Substitute":[ 
              {
                "ddd":"data_roam"
              }
            ],
            "Append":false
          }
  ..],
      "Blocker":false,
      "Weight":10
    }
  ]
}
##
```

Creates a wrong key in datadb and causes error : 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7aa151]

goroutine 110 [running]:
github.com/cgrates/cgrates/utils.(*RSRParser).Compile(0xc42048b980, 0xc4204d5e10, 0xc4205255e8)
        /home/golan/proj/src/github.com/cgrates/cgrates/utils/rsrparser.go:192 +0x61
github.com/cgrates/cgrates/utils.RSRParsers.Compile(0xc42000ea00, 0x1, 0x1, 0x1, 0x1)
        /home/golan/proj/src/github.com/cgrates/cgrates/utils/rsrparser.go:61 +0x4d
github.com/cgrates/cgrates/engine.(*AttributeProfile).compileSubstitutes(0xc4204b8c60, 0xc42056d597, 0x1d)
        /home/golan/proj/src/github.com/cgrates/cgrates/engine/libattributes.go:60 +0x6b
github.com/cgrates/cgrates/engine.(*AttributeProfile).Compile(0xc4204b8c60, 0xc42056d590, 0x6)
        /home/golan/proj/src/github.com/cgrates/cgrates/engine/libattributes.go:70 +0x39
github.com/cgrates/cgrates/engine.(*DataManager).GetAttributeProfile(0xc4203aa920, 0xc42056d590, 0x6, 0xc42056d597, 0x1d, 0xf4f301, 0x0, 0x0, 0xc420525760, 0x446117, ...)
        /home/golan/proj/src/github.com/cgrates/cgrates/engine/datamanager.go:1089 +0x281
github.com/cgrates/cgrates/engine.(*DataManager).CacheDataFromDB(0xc4203aa920, 0x1072709, 0x4, 0xc4205259d0, 0x1, 0x1, 0x1, 0x0, 0xc4204b8bd0)
        /home/golan/proj/src/github.com/cgrates/cgrates/engine/datamanager.go:244 +0x5e8
github.com/cgrates/cgrates/engine.(*DataManager).SetAttributeProfile(0xc4203aa920, 0xc4204b8b40, 0xc420496a01, 0x2, 0x2)
        /home/golan/proj/src/github.com/cgrates/cgrates/engine/datamanager.go:1105 +0x204
github.com/cgrates/cgrates/apier/v1.(*ApierV1).SetAttributeProfile(0xc4204c1700, 0xc4204b8b40, 0xc4203a02c0, 0x0, 0x0)
        /home/golan/proj/src/github.com/cgrates/cgrates/apier/v1/attributes.go:62 +0xaf
reflect.Value.call(0xc4204b0cc0, 0xc42000f818, 0x13, 0x10723b9, 0x4, 0xc420496f20, 0x3, 0x3, 0x1585e00, 0xc420014df8, ...)
        /home/golan/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc4204b0cc0, 0xc42000f818, 0x13, 0xc420167720, 0x3, 0x3, 0x0, 0x0, 0x0)
        /home/golan/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc4204c3f00, 0xc420011fc0, 0xc4203a0088, 0xc4204b5080, 0xc42013ef40, 0xf4f360, 0xc4204b8b40, 0x16, 0xea8aa0, 0xc4203a02c0, ...)
        /home/golan/go/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
        /home/golan/go/src/net/rpc/server.go:481 +0x404
```

### PR DESCRIPTION
**Pull request by TeoV**

### CODE REVIEW

File: apier/v1/attributes.go [hunk 1]
```diff
@@ -59,6 +59,16 @@ func (apierV1 *ApierV1) SetAttributeProfile(alsPrf *engine.AttributeProfile, rep
 	if missing := utils.MissingStructFields(alsPrf, []string{"Tenant", "ID"}); len(missing) != 0 {
 		return utils.NewErrMandatoryIeMissing(missing...)
 	}
+	if len(alsPrf.Attributes) != 0 {
+		for _, attr := range alsPrf.Attributes {
+			for _, sub := range attr.Substitute {
+				if missing := utils.MissingStructFields(sub, []string{"Rules", "AllFiltersMatch"}); len(missing) != 0 {
```
Comment (danbogos) [inline apier/v1/attributes.go]: Please make AllFiltersMatch as optional (ie: if attr.Substitute.Rules == ""...

Comment (danbogos) [reply apier/v1/attributes.go]: Also, I would compile the rule before saving it since there are chances that the rule is wrongly inserted, hence we will inject wrong code in db.

**Comment by danbogos** [comment]
Thanks!
