### PR TITLE
Check error before checking deleteCount fixes #1699

### LINKED ISSUE #1699: Crash: cgr-migrator upon mongo authentication
I see then i set authentication on mongo, my migration starts to fail with below logs. 

`root@home:/# cgr-engine -version
CGRateS 0.9.1~rc8 git+ed29e92 (2019-09-24T13:34:39+03:00)
`

root@home:/usr/share/cgrates/tariffplans/tutorial# cgr-migrator  -stordb_passwd="CGRateS.org"  -stordb_user="cgrates" -stordb_type="*mongo" -stordb_port="27017" -exec="*set_versions" -stordb_host="127.0.0.1"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1057417]

goroutine 1 [running]:
github.com/cgrates/cgrates/engine.(*MongoStorage).RemoveVersions.func1(0x18ce280, 0xc0002bd480, 0x18ce280, 0xc0002bd480)
        /home/teo/go/src/github.com/cgrates/cgrates/engine/storage_mongo_stordb.go:1575 +0x117
go.mongodb.org/mongo-driver/mongo.(*Client).UseSessionWithOptions(0xc0000f2b00, 0x18b6760, 0xc000470de0, 0xc0004c58f0, 0xc0005b5a98, 0x0, 0x0)
        /home/teo/go/src/github.com/cgrates/cgrates/tmp/pkg/mod/go.mongodb.org/mongo-driver@v1.1.1/mongo/client.go:589 +0x1cc
go.mongodb.org/mongo-driver/mongo.(*Client).UseSession(...)
        /home/teo/go/src/github.com/cgrates/cgrates/tmp/pkg/mod/go.mongodb.org/mongo-driver@v1.1.1/mongo/client.go:571
github.com/cgrates/cgrates/engine.(*MongoStorage).query(0xc000376200, 0xc0005b5a98, 0x0, 0x0)
        /home/teo/go/src/github.com/cgrates/cgrates/engine/storage_mongo_datadb.go:224 +0x106
github.com/cgrates/cgrates/engine.(*MongoStorage).RemoveVersions(0xc000376200, 0x0, 0xc000512c10, 0xc0002bd420)
        /home/teo/go/src/github.com/cgrates/cgrates/engine/storage_mongo_stordb.go:1573 +0x68
github.com/cgrates/cgrates/engine.(*MongoStorage).SetVersions(0xc000376200, 0xc0004c58c0, 0x1, 0xc0004c58c0, 0x0)
        /home/teo/go/src/github.com/cgrates/cgrates/engine/storage_mongo_stordb.go:1555 +0xa3
github.com/cgrates/cgrates/engine.setDBVersions(0x18cbc40, 0xc000376200, 0xc000376201, 0x18cbc40, 0xc000376200)
        /home/teo/go/src/github.com/cgrates/cgrates/engine/version.go:98 +0x9d
github.com/cgrates/cgrates/engine.OverwriteDBVersions(...)
        /home/teo/go/src/github.com/cgrates/cgrates/engine/version.go:110
github.com/cgrates/cgrates/migrator.(*Migrator).Migrate(0xc0005b5f00, 0xc000123870, 0x1, 0x1, 0x0, 0x0, 0xc000123870)
        /home/teo/go/src/github.com/cgrates/cgrates/migrator/migrator.go:84 +0x3626
main.main()
        /home/teo/go/src/github.com/cgrates/cgrates/cmd/cgr-migrator/cgr-migrator.go:350 +0x148e

```
MongoDB shell version v4.2.0
git version: a4b751dcf51dd249c5865812b390cfd1c0129c30
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
allocator: tcmalloc
modules: none
build environment:
    distmod: debian92
    distarch: x86_64
    target_arch: x86_64
```

### PR DESCRIPTION
**Pull request by TeoV**

### CODE REVIEW

File: engine/storage_mongo_stordb.go [hunk 1]
```diff
@@ -1572,10 +1572,13 @@ func (ms *MongoStorage) RemoveVersions(vrs Versions) (err error) {
 	if len(vrs) == 0 {
 		return ms.query(func(sctx mongo.SessionContext) (err error) {
 			dr, err := ms.getCol(ColVer).DeleteOne(sctx, bson.D{})
```
Comment (danbogos) [inline engine/storage_mongo_stordb.go]: if you are returning default error here, out of good practice please don't use := but = when capturing err

**Comment by danbogos** [comment]
Thanks!
