### PR TITLE
TPReader replace ParseDate with ParseTimeDetectlayout fixes #1331

### LINKED ISSUE #1331: Cgrates not recognizing negative UTC offsets in valid RFC3339 datetime format
It appears that Cgrates does not check for one of the types of valid RFC3339 timedate formats.  We are using debian 9 to reproduce. Assuming you have a MySQL storDB configured with a row that has tpid="b1", activation_time column is datetime type, and saved as "2018-11-24 08:00:00"
```
timedatectl set-timezone America/Los_Angeles
systemctl restart cgrates

# cgr-console
cgr> load_tp_from_stordb TPid="b1" FlushDb=false DryRun=true Validate=false Cleanup=false
Error executing command: SERVER_ERROR: cannot parse activation time from 2018-11-24T08:00:00-08:00
exit

timedatectl set-timezone America/New_York
systemctl restart cgrates

# cgr-console
cgr> load_tp_from_stordb TPid="b1" FlushDb=false DryRun=true Validate=false Cleanup=false
Error executing command: SERVER_ERROR: cannot parse activation time from 2018-11-24T08:00:00-05:00
exit

timedatectl set-timezone UTC
systemctl restart cgrates

# cgr-console
cgr> load_tp_from_stordb TPid="b1" FlushDb=false DryRun=true Validate=false Cleanup=false
"OK"
exit

timedatectl set-timezone Europe/Berlin
systemctl restart cgrates

# cgr-console
cgr> load_tp_from_stordb TPid="b1" FlushDb=false DryRun=true Validate=false Cleanup=false
"OK"
```
It looks like the problem may be here
https://github.com/cgrates/cgrates/blob/d4129d1c775e433f72a558464d2be8419715e4c0/utils/coreutils.go#L260

which does not appear to check for negative timezone offsets that are in valid RFC3339 format.

Here is an example of some code that checks for negative timezone offsets. 
 https://play.golang.org/p/HiikqFKdYBZ
```
package main

import (
    "fmt"
    "time"
    "math"
)

func main() {
    date := "2018-12-03T22:23:22-01:00"
    t, err := time.Parse(time.RFC3339, date)
    _, tzOffset:= t.Zone()
    i := float64(tzOffset)
    fmt.Println(tzOffset)
    fmt.Println("Is it negative: ", math.Signbit(i)) 
    if err != nil {
		fmt.Println("error", err)
		return
	}
}
```

### PR DESCRIPTION
**Pull request by TeoV**

### CODE REVIEW

File: utils/coreutils_test.go [hunk 1]
```diff
@@ -257,73 +257,60 @@ func TestParseTimeDetectLayout(t *testing.T) {
...
 	if err != nil || date.Sub(expected).Seconds() > 20 || date.Sub(expected).Seconds() < 19 {
 		t.Error("error parsing date: ", date.Sub(expected).Seconds())
 	}
-}
 
-func TestParseDateMonthly(t *testing.T) {
-	expected := time.Now().AddDate(0, 1, 0)
-	if date, err := ParseDate("*monthly"); err != nil {
+	expected = time.Now().AddDate(0, 1, 0)
+	if date, err := ParseTimeDetectLayout("*monthly", ""); err != nil {
```
Comment (danbogos) [inline utils/coreutils_test.go]: please replace *monthly with it's constant, so we can be consistent

**Comment by danbogos** [comment]
Thanks!
